### ISSUE TITLE
Pedido Limpieza UC3M 16 viseras + 25 sujetas

### ISSUE THREAD

**Issue by rcastellanosgdb** [roboticslab-uc3m/covid19-fablab#108]
Entregadas!!

**Comment by VentressAsajj** [comment]
@rcastellanosgdb en mks han entragado otras 10. Al principio se le dijo a la encargada que cuantas querían y les dimos las que nos pidió. Voy a hablar con la encargada que nos digan todas las que quieren para apuntarlas. @jgvictores cierra por favor.
