### ISSUE TITLE
Hospitales y resis (320)

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/covid19-fablab#11]
- 12 de Octubre (100)
- Hosp. Mostoles (100)
- Residencia Carabanchel (20)
- Hos. Clinico San Carlos (100)

**Comment by dgmato** [comment]
Hospital Universitario 12 de Octubre (125)
Hospital Universitario de Móstoles (100)
Residencia Monte Hermoso (25)

**Comment by dgmato** [comment]
Entregadas!
