### ISSUE TITLE
Pedido sujetamascarillas Hos. Gregorio Marañón

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/covid19-fablab#28]
pedido:1200
contacto: @Ventress
referencia: Lab, Diego

**Comment by jgvictores** [comment]
Entrega 400 añadido en https://github.com/roboticslab-uc3m/covid19-fablab/commit/73f7d843012527f7438551a7280302db1165fd2b, dejo abierto de momento.

**Comment by dgmato** [comment]
800 entregadas
