### ISSUE TITLE
Pedido sujetamascarillas Hos. Gregorio Marañón (1000)

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/covid19-fablab#42]
elemento: sujetamascarillas
pedido:1000
contacto: @Ventress
referencia: Lab, Diego

**Comment by diegotrap** [comment]
Muchas gracias chicos!

**Comment by jgvictores** [comment]
Entregadas 600/1000. Espero a entrega final mañana antes de anotar en tabla.

**Comment by jgvictores** [comment]
Entregadas las otras 400, total 1000 listo para tabla.
