### ISSUE TITLE
Pedido 50 pantallas Centro de Salud 2 de Mayo Móstoles

### ISSUE THREAD

**Issue by VentressAsajj** [roboticslab-uc3m/covid19-fablab#75]
Pedido: 50 pantallas
contacto: @venress
Lugar de entrega: Centro de Salud 2 de Mayo, c/ Coronel de  Palma, Mostoles hasta las 8 de la tarde.
Contactado via twitter

**Comment by VentressAsajj** [comment]
Gestionado transporte. Recogida día 29 a la 12 en Leganés.

**Comment by jgvictores** [comment]
Entregadas
