### ISSUE TITLE
Pedido 16 pantallas UVI 20 San Martín de Valdeiglesias 

### ISSUE THREAD

**Issue by fjfransa** [roboticslab-uc3m/covid19-fablab#82]
Soy francisco de la oficina técnica... yo me encargo de entregar las pantallas...

**Comment by jgvictores** [comment]
Oks! @fjfransa porfa avisa cuando hayas entregado!

**Comment by VentressAsajj** [comment]
entregadas @jgvictores cierra

**Comment by fjfransa** [comment]
Ya entregadas
